Part 2
SozonikOleg/reactjs-films-homework pull request #2
Opened 2019-04-11 14:08 UTC by SozonikOleg

2019-04-11 14:37 UTC, RamanRudski requested changes

2019-04-11 14:37 UTC, Erromanr commented on src/components/App/App.jsx
> +class App extends Component {
Это stateless component. Используй функциональный компонет а не класс. [unction-and-class-components](https://reactjs.org/docs/components-and-props.html#function-and-class-components) тебе здесь не нужны все вещи которые ты наследуешь от `React.Component` ты просто отображаешь `props`.

2019-04-11 14:37 UTC, Erromanr commented on src/components/Header/Header.jsx
> +class Header extends Component {
It is stateless component

2019-04-11 14:37 UTC, Erromanr commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                <li><a href="#">Fantasy</a></li>
Сделай массив жанров и пройдись по нему при помощи `map` и отрендери. [for example](https://reactjs.org/docs/lists-and-keys.html#rendering-multiple-components)

2019-04-11 14:37 UTC, Erromanr commented on src/components/HeaderInfo/HeaderInfo.jsx
> +            < FontAwesomeIcon icon="star" className={styles.star}/>
Смотри комментарий выше

2019-04-11 14:37 UTC, Erromanr commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                        Similique culpa repellat molestiae vel?
Весь текст вынеси в переменную. Или сделай отдельный файл например `mock.js` там где будут все эти константные значения.

2019-04-11 14:37 UTC, Erromanr commented on src/components/Search/Search.jsx
> +class Search extends Component {
It is stateless component

2019-04-13 23:33 UTC, SozonikOleg commented on src/components/App/App.jsx
> +class App extends Component {
Пофиксил

2019-04-13 23:33 UTC, SozonikOleg commented on src/components/Header/Header.jsx
> +class Header extends Component {
Пофиксил

2019-04-13 23:33 UTC, SozonikOleg commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                <li><a href="#">Fantasy</a></li>
Пофиксил

2019-04-13 23:34 UTC, SozonikOleg commented on src/components/Search/Search.jsx
> +class Search extends Component {
пофиксил

2019-04-13 23:39 UTC, SozonikOleg commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                        Similique culpa repellat molestiae vel?
Пофиксил

2019-04-14 00:04 UTC, SozonikOleg commented on src/components/HeaderInfo/HeaderInfo.jsx
> +            < FontAwesomeIcon icon="star" className={styles.star}/>
Пофиксил

2019-04-16 07:45 UTC, RamanRudski approved these changes

2019-04-16 07:46 UTC, merged