Part 4
SozonikOleg/reactjs-films-homework pull request #4
Opened 2019-05-27 08:41 UTC by SozonikOleg

2019-05-31 09:51 UTC, RamanRudski requested changes

2019-05-31 09:51 UTC, Erromanr commented on src/action/GenreActionList/getActionGenre.js
> +    'https://api.themoviedb.org/3/discover/movie?api_key=d930c628f4aadc8b0b06359a9cf7230d&with_genres=28',
Url нужно вынести в константу. И использовать уже ее. 
Сделать во всеми url.

2019-05-31 09:51 UTC, Erromanr commented on src/action/GenreActionList/getWesternGenre.js
> +};
У тебя экшен для каждого жанра. Каждый этот экшен выполняет одно и тоже и отличаеться только кодом жанра. 
Нарушается принцип DRY (don't repeat yourself ). 
Сделай только один эшен , который будет получать параметром нужный ему код жанра.

2019-05-31 09:51 UTC, Erromanr commented on src/components/Header/Header.jsx
> +        backgroundSize: 'cover',
этот обьект вынеси в переменную, выше.

2019-05-31 09:51 UTC, Erromanr commented on src/components/HeaderInfo/HeaderInfo.jsx
> +const icons = ['star', 'star', 'star', 'star', 'star'];
Такого быть не должно. Придумай другую реализацию. 
Непонятно зачем использовать массив с одинаковыми элементами.

2019-05-31 09:51 UTC, Erromanr commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                <li key={index}>
`key={index}` нежелательно.

2019-05-31 09:51 UTC, Erromanr commented on src/components/MovieItem/MovieItem.jsx
> +    this.setState({ itemState: false });
`setState`  нужно использовать здесь 1 раз. 
`setState({
isOpened: !this.state.isOpened,
itemState: false,
....
})`

2019-05-31 09:51 UTC, Erromanr commented on src/components/Search/Search.jsx
> +    document.getElementById("myForm").reset();
используй `ref` не нужно обращаться к DOM на прямую

2019-05-31 09:51 UTC, Erromanr commented on src/components/TitleMain/TitleMain.jsx
> +            <ul className={styles.submenu}>
1. Когда переделаешь экшен и он станет один , файл станет меньше вдвое.
2. Создай массив жанров. Проходя по нему создавай `<li> </li>`.
3. И хэндлер тоже будет один. Которому ты передаёшь жанр.

2019-05-31 13:39 UTC, SozonikOleg commented on src/action/GenreActionList/getActionGenre.js
> +    'https://api.themoviedb.org/3/discover/movie?api_key=d930c628f4aadc8b0b06359a9cf7230d&with_genres=28',
Пофиксил

2019-05-31 13:40 UTC, SozonikOleg commented on src/action/GenreActionList/getWesternGenre.js
> +};
Пофиксил

2019-05-31 13:47 UTC, SozonikOleg commented on src/components/Header/Header.jsx
> +        backgroundSize: 'cover',
Пофиксил

2019-05-31 15:15 UTC, SozonikOleg commented on src/components/HeaderInfo/HeaderInfo.jsx
> +const icons = ['star', 'star', 'star', 'star', 'star'];
Пофиксил

2019-05-31 16:58 UTC, SozonikOleg commented on src/components/HeaderInfo/HeaderInfo.jsx
> +                <li key={index}>
Пофиксил

2019-05-31 17:14 UTC, SozonikOleg commented on src/components/MovieItem/MovieItem.jsx
> +    this.setState({ itemState: false });
Пофиксил

2019-06-03 06:52 UTC, SozonikOleg commented on src/components/MovieItem/MovieItem.jsx
> +    this.setState({ itemState: false });
Пофиксил

2019-06-03 07:03 UTC, SozonikOleg commented on src/components/Search/Search.jsx
> +    document.getElementById("myForm").reset();
Пофиксил

2019-06-04 13:56 UTC, SozonikOleg commented on src/components/Search/Search.jsx
> +    document.getElementById("myForm").reset();
Пофиксил

2019-06-04 13:56 UTC, SozonikOleg commented on src/components/TitleMain/TitleMain.jsx
> +            <ul className={styles.submenu}>
Пофиксил

2019-06-10 08:15 UTC, merged